version: '3.3'

services:

  #############################################################
  ######################### APP ###############################
  #############################################################

  clock-love-app: 
    container_name: clock-love-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"